FROM registry.opensuse.org/opensuse/tumbleweed

RUN zypper --non-interactive install salt-master && \
    rm -rf /var/cache/yum

RUN sed -i "s|#auto_accept: False|auto_accept: True|g" /etc/salt/master

CMD ["salt-master", "-l", "debug"]
